// data.js - Handles loading and managing quiz data

// Initial quiz data structure
const quizData = {
    lastUpdated: "2025-06-11T20:00:00",
    teams: [
        { id: 1, name: "Kokken,Tyven, hans kone og hennes elskere" },
        { id: 2, name: "Quizly Bears" },
        { id: 3, name: "Knut sine høner" },
        { id: 4, name: "Quiz my ass" },
        { id: 5, name: "I siste liten" },
        { id: 6, name: "No Fun Intended" },
        { id: 7, name: "Just happy to be here" },
        { id: 8, name: "Quizimilis" },
        { id: 9, name: "Ikke ta meg på Quizen" },
        { id: 10, name: "Vi jobber med saken" },
        { id: 11, name: "Pedro Castillo" },
        { id: 12, name: "Victors Våtfor & B'N'B" },
        { id: 13, name: "Mafia" },
        { id: 14, name: "Tusseladdene" },
        { id: 15, name: "Rolig som skjæra på tunet" },
        { id: 16, name: "404" },
        { id: 17, name: "Lavterskel" },
        { id: 18, name: "Tone's dispipler" },
        { id: 19, name: "Tøvsjurer og andre fuglearter" },
        { id: 20, name: "Titanics" },
        { id: 21, name: "Quiz my baby one more time 1" },
        { id: 22, name: "Bjørnens hule" },
        { id: 23, name: "Mølje" },
        { id: 24, name: "Uvitenskap!" },
        { id: 25, name: "Kjetil Heit!" },
        { id: 26, name: "Spice girls 1" },
        { id: 27, name: "FK Kad (Rigomor Supporterklubb)" },
        { id: 28, name: "Fernet" },
        { id: 29, name: "Slick" },
        { id: 30, name: "Lady Bugs" },
        { id: 31, name: "Portvin 2" },
        { id: 32, name: "Quiz my baby one more time 2" },
        { id: 33, name: "Team Lund" },
        { id: 34, name: "Catalans" },
        { id: 35, name: "The Thee Musketeers" },
        { id: 36, name: "Peter Lorenkrantz disipler" },
        { id: 37, name: "Southampton 24/25" },
        { id: 38, name: "Træff på Quiz" },
        { id: 39, name: "A-laget" },
        { id: 40, name: "The Skibidi Ben Dovers" },
        { id: 41, name: "Pannekake Profetene" },
        { id: 42, name: "Vil På Spa" },
        { id: 43, name: "Flesk og Duppe" },
        { id: 44, name: "Taschlkailan" },
        { id: 45, name: "Over Minstemålet" },
        { id: 46, name: "Det e komplisert" },
        { id: 47, name: "Post Quizz Clarity" },
        { id: 48, name: "Stolpe i raden" },
        { id: 49, name: "VKSNPPLRNG" },
        { id: 50, name: "Low 5" },
        { id: 51, name: "Soletti" },
        { id: 52, name: "Yo Gult" },
    ],
    rounds: [
        { id: 1, number: 1, date: "2025-02-14" },
        { id: 2, number: 2, date: "2025-02-28" },
        { id: 3, number: 3, date: "2025-03-14" },
        { id: 4, number: 4, date: "2025-03-28" },
        { id: 5, number: 5, date: "2025-04-11" },
        { id: 6, number: 6, date: "2025-04-25" },
        { id: 7, number: 7, date: "2025-05-09" },
        { id: 8, number: 8, date: "2025-05-23" },
        { id: 9, number: 9, date: "2025-06-06" },
        { id: 10, number: 10, date: "2025-06-20" }
    ],
    scores: [
        // Round 1 (Feb 14)
        { teamId: 1, roundId: 1, score: 12 },
        { teamId: 2, roundId: 1, score: 7 },
        { teamId: 4, roundId: 1, score: 7 },
        { teamId: 5, roundId: 1, score: 3 },
        { teamId: 6, roundId: 1, score: 1 },
        { teamId: 7, roundId: 1, score: 10 },
        { teamId: 8, roundId: 1, score: 3 },
        { teamId: 11, roundId: 1, score: 7 },
        { teamId: 12, roundId: 1, score: 10 },
        { teamId: 14, roundId: 1, score: 7 },
        { teamId: 17, roundId: 1, score: 1 },
        { teamId: 19, roundId: 1, score: 1 },
        { teamId: 23, roundId: 1, score: 1 },
        { teamId: 24, roundId: 1, score: 1 },
        { teamId: 25, roundId: 1, score: 1 },
        
        // Round 2 (Feb 28)
        { teamId: 1, roundId: 2, score: 12 },
        { teamId: 2, roundId: 2, score: 12 },
        { teamId: 4, roundId: 2, score: 4 },
        { teamId: 5, roundId: 2, score: 7 },
        { teamId: 6, roundId: 2, score: 8 },
        { teamId: 7, roundId: 2, score: 6 },
        { teamId: 8, roundId: 2, score: 1 },
        { teamId: 9, roundId: 2, score: 6 },
        { teamId: 10, roundId: 2, score: 4 },
        { teamId: 11, roundId: 2, score: 1 },
        { teamId: 13, roundId: 2, score: 1 },
        { teamId: 17, roundId: 2, score: 2 },
        { teamId: 18, roundId: 2, score: 4 },
        { teamId: 19, roundId: 2, score: 1 },
        { teamId: 22, roundId: 2, score: 1 },
        { teamId: 26, roundId: 2, score: 1 },
        { teamId: 27, roundId: 2, score: 1 },
        { teamId: 28, roundId: 2, score: 1 },
        { teamId: 29, roundId: 2, score: 1 },
        
        // Round 3 (Mar 14)
        { teamId: 1, roundId: 3, score: 8 },
        { teamId: 2, roundId: 3, score: 10 },
        { teamId: 3, roundId: 3, score: 12 },
        { teamId: 4, roundId: 3, score: 3 },
        { teamId: 5, roundId: 3, score: 5 },
        { teamId: 7, roundId: 3, score: 1 },
        { teamId: 8, roundId: 3, score: 3 },
        { teamId: 9, roundId: 3, score: 1 },
        { teamId: 11, roundId: 3, score: 3 },
        { teamId: 13, roundId: 3, score: 1 },
        { teamId: 14, roundId: 3, score: 1 },
        { teamId: 15, roundId: 3, score: 7 },
        { teamId: 17, roundId: 3, score: 7 },
        { teamId: 16, roundId: 3, score: 4 },
        { teamId: 20, roundId: 3, score: 1 },
        { teamId: 30, roundId: 3, score: 1 },
        
        // Round 4 (Mar 28)
        { teamId: 1, roundId: 4, score: 12 },
        { teamId: 2, roundId: 4, score: 8 },
        { teamId: 3, roundId: 4, score: 10 },
        { teamId: 5, roundId: 4, score: 5 },
        { teamId: 6, roundId: 4, score: 6 },
        { teamId: 7, roundId: 4, score: 1 },
        { teamId: 8, roundId: 4, score: 8 },
        { teamId: 11, roundId: 4, score: 1 },
        { teamId: 13, roundId: 4, score: 4 },
        { teamId: 15, roundId: 4, score: 1 },
        { teamId: 16, roundId: 4, score: 3 },
        { teamId: 17, roundId: 4, score: 2 },
        { teamId: 19, roundId: 4, score: 1 },
        { teamId: 20, roundId: 4, score: 2 },
        { teamId: 21, roundId: 4, score: 1 },
        { teamId: 22, roundId: 4, score: 1 },
        { teamId: 31, roundId: 4, score: 1 },
        
        // Round 5 (Apr 11)
        { teamId: 1, roundId: 5, score: 12 },
        { teamId: 2, roundId: 5, score: 8 },
        { teamId: 3, roundId: 5, score: 6 },
        { teamId: 4, roundId: 5, score: 12 },
        { teamId: 5, roundId: 5, score: 1 },
        { teamId: 6, roundId: 5, score: 4 },
        { teamId: 8, roundId: 5, score: 2 },
        { teamId: 9, roundId: 5, score: 6 },
        { teamId: 10, roundId: 5, score: 8 },
        { teamId: 13, roundId: 5, score: 3 },
        { teamId: 17, roundId: 5, score: 1 },
        { teamId: 19, roundId: 5, score: 1 },        
        { teamId: 21, roundId: 5, score: 1 },
        { teamId: 32, roundId: 5, score: 1 },
        { teamId: 33, roundId: 5, score: 1 },
        { teamId: 34, roundId: 5, score: 1 },
        { teamId: 35, roundId: 5, score: 1 },
        { teamId: 36, roundId: 5, score: 1 },
        { teamId: 37, roundId: 5, score: 1 },
        { teamId: 38, roundId: 5, score: 1 },
        { teamId: 39, roundId: 5, score: 1 },
        { teamId: 40, roundId: 5, score: 1 },
        { teamId: 41, roundId: 5, score: 1 },

        //Round 6 (Apr 25)
        { teamId: 1, roundId: 6, score: 12 },
        { teamId: 2, roundId: 6, score: 7 },
        { teamId: 3, roundId: 6, score: 10 },
        { teamId: 4, roundId: 6, score: 3 },
        { teamId: 5, roundId: 6, score: 1 },
        { teamId: 6, roundId: 6, score: 1 },
        { teamId: 7, roundId: 6, score: 1 },
        { teamId: 8, roundId: 6, score: 6 },
        { teamId: 10, roundId: 6, score: 8 },
        { teamId: 11, roundId: 6, score: 5 },        
        { teamId: 13, roundId: 6, score: 1 },
        { teamId: 17, roundId: 6, score: 4 },        
        { teamId: 20, roundId: 6, score: 1 },        
        { teamId: 22, roundId: 6, score: 3 },  
        { teamId: 42, roundId: 6, score: 1 },        
        { teamId: 43, roundId: 6, score: 1 },
        
        //Round 7 (May 9)
        { teamId: 1, roundId: 7, score: 10 },
        { teamId: 2, roundId: 7, score: 10 },
        { teamId: 3, roundId: 7, score: 12 },
        { teamId: 4, roundId: 7, score: 7 },
        { teamId: 5, roundId: 7, score: 4 },        
        { teamId: 7, roundId: 7, score: 1 },
        { teamId: 8, roundId: 7, score: 3 },
        { teamId: 9, roundId: 7, score: 5 },
        { teamId: 13, roundId: 7, score: 3 },
        { teamId: 15, roundId: 7, score: 1 },        
        { teamId: 17, roundId: 7, score: 6 },
        { teamId: 20, roundId: 7, score: 3 },
        { teamId: 21, roundId: 7, score: 3 },
        { teamId: 33, roundId: 7, score: 1 },        
        { teamId: 44, roundId: 7, score: 1 },
        { teamId: 45, roundId: 7, score: 1 },
        { teamId: 46, roundId: 7, score: 1 },   
        // Round 6-10 (Apr 25 - Jun 20) - Add future rounds here
        
        //Round 8
        { teamId: 1, roundId: 8, score: 10 },
        { teamId: 2, roundId: 8, score: 8 },
        { teamId: 3, roundId: 8, score: 12 },
        { teamId: 4, roundId: 8, score: 3 },
        { teamId: 5, roundId: 8, score: 5 },
        { teamId: 6, roundId: 8, score: 1 },  
        { teamId: 8, roundId: 8, score: 6 },
        { teamId: 13, roundId: 8, score: 1 },
        { teamId: 14, roundId: 8, score: 1 },
        { teamId: 17, roundId: 8, score: 5 },
        { teamId: 20, roundId: 8, score: 1 },
        { teamId: 47, roundId: 8, score: 10 },
        { teamId: 48, roundId: 8, score: 7 },
        { teamId: 49, roundId: 8, score: 2 },
        
        //Round 9
        { teamId: 1, roundId: 9, score: 8 },
        { teamId: 2, roundId: 9, score: 12 },
        { teamId: 3, roundId: 9, score: 8 },
        { teamId: 4, roundId: 9, score: 3 },
        { teamId: 5, roundId: 9, score: 4 },
        { teamId: 8, roundId: 9, score: 5 },
        { teamId: 9, roundId: 9, score: 5 },
        { teamId: 17, roundId: 9, score: 7 },
        { teamId: 20, roundId: 9, score: 4 },
        { teamId: 48, roundId: 9, score: 6 },       
        { teamId: 51, roundId: 9, score: 2 },
        { teamId: 52, roundId: 9, score: 3 }

    ]
};

// Export the data
export { quizData };
